### ISSUE TITLE
Leiningen template

### ISSUE THREAD

**Issue by jellea** [mjmeintjes/boot-react-native#12]
Would be great to have a leiningen template to get started quickly. Currently you would have to copy the example and edit namespaces/folders to taste.

**Comment by pesterhazy** [comment]
Recent https://github.com/seancorfield/boot-new might be worth checking out

**Comment by jellea** [comment]
Started with this, check it out [here.](https://github.com/jellea/react-native-boot-template) Got iOS working (although still broken in Clojars due to resources folder completely missing in jar), but Android is bit of a hassle due to a couple of binaries present and the gradle jar causing the template build to fail. Also the snapshot of boot-react-native in Clojars is not up to date with master.

**Comment by jellea** [comment]
Uploaded it to Clojars and iOS should be working now. When things look stable I'll drop in a reference in the README of this repo and close this issue.

Give it a try:
```
boot -d seancorfield/boot-new new -S -t boot-react-native -n your-brand-new-app
```

**Comment by pesterhazy** [comment]
@jellea an update of the `boot` template to BRN 0.3 (based on SimpleExampleApp) would be great

**Comment by jellea** [comment]
Is now the time? :) Any upcoming changes?

**Comment by pesterhazy** [comment]
I think we need to start by polishing SimpleExampleApp in a few ways:

- use repl only if it really works (and show how)
- update dependencies
- update cljs version

Maybe we should also automate patching node_modules/react-native

**Comment by pesterhazy** [comment]
I'd argue that copying SimpleExampleApp is simpler right now, feel free to re-open then template is updated, I'll add it to the docs then.
