### ISSUE TITLE
Hacking on the boot task

### ISSUE THREAD

**Issue by pesterhazy** [mjmeintjes/boot-react-native#13]
This is more of a question than an issue. How do you hack on the boot task (`*.clj` or `resources/*`) without building a new jar for every change? That seems a bit tedious. I wondered if boot's checkout task is useful (I'm hearing this will be improved in an upcoming version), or if it's possible to include the `src` path directly in a (copy of?) the example app.

**Comment by mjmeintjes** [comment]
The `boot dev` command watches for source code changes, builds the boot-react-native task and installs the jar locally in less than a second. Just run it from the root directory in one terminal, and then open another terminal to work on the example app. Each time you run `boot fast-build` it'll then automatically pick up the latest changes.

Another tip - use `(debug-repl)` to open up a repl with local context while developing - I've found that really useful to inspect the state of the boot task while running. Let me know if you want more detail.
