### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mjmeintjes** [mjmeintjes/boot-react-native#31]
A lot of new changes and upgrades have been made to boot-react-native, especially on the iOS side.

- [x] Merge in outstanding pull requests
- [x] Write changelog for new release
- [x] Update documentation on how to use new tasks/features
- [x] Create new Github release
- [x] Publish to clojars

**Comment by jellea** [comment]
Whats the status? Will be pointing people to brn+template in two talks this week, first being one this Thursday. Think it would be nice to have all the niceties in place :) Thanks!

**Comment by mjmeintjes** [comment]
I was just waiting for one pull request to be fixed - expect new release today.

**Comment by mjmeintjes** [comment]
Released 0.2-SNAPSHOT

**Comment by jellea** [comment]
Great! Thanks!
