### ISSUE TITLE
Remove boot-reload shims

### ISSUE THREAD

**Issue by mjmeintjes** [mjmeintjes/boot-react-native#37]
See https://github.com/adzerk-oss/boot-reload/pull/58. New features included in boot-reload means we can remove `shim-boot-reload`.

**Comment by pesterhazy** [comment]
Agree, should not be needed anymore.

However, I've been seeing "undefined is not an object" errors in the `boot-reload` code, on reload, with the released version of `boot-reload` 0.4.5. It works with https://github.com/pesterhazy/boot-reload/tree/fix/react-native, so maybe it's related to one of the commits that went in after my fix.

**Comment by pesterhazy** [comment]
Here's what I see, basically `undefined is not an object (near '...,js_files))).addCallbacks(((func...')`:

 ![screen shot 2016-02-16 at 18 47 34](https://cloud.githubusercontent.com/assets/106328/13085301/d3d61434-d4dd-11e5-843e-d146c088e017.png)
