### ISSUE TITLE
`boot dev` starts vim

### ISSUE THREAD

**Issue by pesterhazy** [mjmeintjes/boot-react-native#38]
A curious issue: when I run `boot dev` in my project, it ends ups starting `vim` somewhere along the way. You can sort of see it, syntax highlighting and all. Compilation still works, but it scrolls only on half the screen in my terminal.

Obviously no interactive program should be launched during `boot dev`.

I think it happens when there are warnings. Maybe it's the `react packager`? Very mysterious.

This is in my own project, but don't see how anything specific of this project would cause this.

**Comment by mjmeintjes** [comment]
Interesting. Can you post a screenshot and some more details, like your platform and your `dev` task pipeline.

**Comment by pesterhazy** [comment]
Will do when I see it again. Should also try to replicate it with SimpleExampleApp.

**Comment by pesterhazy** [comment]
Apparently this is what the react-native packager does when you click on lines of the stack trace on the red screen: https://github.com/facebook/react-native/blob/e08a7f35876cf102a6453273a71d8664debfb55c/local-cli/server/util/launchEditor.js It sort of guesses an editor type (based on `ps x`) and runs it.

Frankly this seems bizarre default behavior for a packaging tool. Also there seems to be no way to disable this in non-interactive use (as with b-r-n).

The easiest solution for now I guess is not to click on the stack trace in the simulator.

**Comment by pesterhazy** [comment]
As of 0.3 we're not starting the packager inside the `boot` process anymore, so not as much an issue anymore.

By the way, I've found it's best to set REACT_EDITOR to some graphical editor like `emacsclient` or `gvim` that does *not* open in the terminal.
