### ISSUE TITLE
`dependencies` task

### ISSUE THREAD

**Issue by pesterhazy** [mjmeintjes/boot-react-native#41]
It would be useful to have a `dependencies` boot task that verifies that external dependencies are present.

For SimpleExampleApp:
- runs `npm install` in `app/` if it hasn't been run before
- possibly check that `npm` and `node` are recent enough

This could be optimized by adding a file that is updated with the content hash of `package.json` if `npm install` succeeds. Then checking if `npm install` needs to be re-run would be as simple as comparing the hash to the file.

I've implemented this successfully before. Do you think this would be useful as part of the example app? It would be a step towards `boot dev` being a single-command dev environment.

**Comment by mjmeintjes** [comment]
I'm happy for something like this to be added. 

Another idea I've thought about is being able to specify React Native modules in build.boot, and then automatically adding them to package.json, and any other places they need to be added (for Android, in MainActivity.java and gradle files, not sure about iOS). 

But that would take more work, and the first step would definitely be to get the `dependencies` boot task in.
