### ISSUE TITLE
add-bundle.sh fails when boot dist has not been called

### ISSUE THREAD

**Issue by aiba** [mjmeintjes/boot-react-native#43]
I just cloned the repo and followed the instructions to run the example app (ios), but the XCode project fails with error:

```
cp: /Users/aiba/boot-react-native/example/app/dist/main.jsbundle: No such file or directory
```

I eventually realized that running `boot dist` solves this, but this was unclear from the instructions because I was only interested in a running in dev mode.

It looks like the line of AppDelegate.m that loads the bundle is commented out anyway:

```
  // jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
```

So, would it make sense to modify add-bundle.sh to not copy the bundle if it doesn't exist?  For example:

```bash
    if [ -f "$bundle" ]; then
        cp "$bundle" "$dest"
    fi
```

Happy to submit a PR if this seems sensible.

**Comment by pesterhazy** [comment]
@alba, thanks for the report. You're right about this I think.

Ideally 1. the bundle should be copied only in Release configuration and 2. the offline bundle should automatically used in Release configuration. However, just not copying the file if it's not there would be a good fix for now. A PR would be welcome.

**Comment by pesterhazy** [comment]
Went ahead and added a PR
