### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by pesterhazy** [mjmeintjes/boot-react-native#51]
There's a couple of ways in which the docs currently fall short.

- [ ] Mention that you need to DISABLE Live Reload in the RN dev menu

**Comment by kennyjwilli** [comment]
This needs to be done on a per app basis for those using Genymotion. Not sure if this needs to be done for Google's emulator.

**Comment by pesterhazy** [comment]
actually we need to disable live reload and hot reloading :)

**Comment by pesterhazy** [comment]
Working on a blog post to fill the documentation gap: https://github.com/pesterhazy/presumably/blob/master/posts/boot-react-native.md -- any feedback welcome!
