### ISSUE TITLE
Update example app

### ISSUE THREAD

**Issue by pesterhazy** [mjmeintjes/boot-react-native#52]
The example app is out of date:

- use a recent React Native
- use new boot

**Comment by mjmeintjes** [comment]
Thanks for this. Yes, I'm planning to go through and update to the latest version some time this week, as I've been a bit busy with the back end/website part of my own app. If you are planning on working on this, just let me know about your progress/issues that crop up.

**Comment by pesterhazy** [comment]
fixed in master
