### ISSUE TITLE
boot-reload hud errors on reload

### ISSUE THREAD

**Issue by pesterhazy** [mjmeintjes/boot-react-native#54]
There are still issues with `boot-reload`'s "hud" display typically shown on reload. This is what I see when I change a file in SimpleExampleApp:

```
Jun  1 09:49:40 Pauluss-MacBook-Air SimpleExampleApp[10756]: createElement is faked - see goog/base.js
Jun  1 09:49:40 Pauluss-MacBook-Air SimpleExampleApp[10756]: undefined is not an object (evaluating 'element.style')
Jun  1 09:49:40 Pauluss-MacBook-Air SimpleExampleApp[10756]: Unhandled JS Exception: undefined is not an object (evaluating 'element.style')
```

I thought that this was fixed by https://github.com/adzerk-oss/boot-reload/pull/58 but it doesn't look like it. I've tried bumping the boot-reload version in build.boot and setting `disable-hud`, but both didn't work.

Not sure why `has-dom?` in boot-reload doesn't appear to work. 

![screen shot 2016-06-01 at 09 52 11](https://cloud.githubusercontent.com/assets/106328/15702146/ae16b510-27de-11e6-86a0-e6aa3a8c8d3f.png)

**Comment by pesterhazy** [comment]
Should be fixed with #55

**Comment by pesterhazy** [comment]
Fixed with recent boot-reload

**Comment by vikeri** [comment]
Got this error now 🙁  Using `boot-reload "0.4.12"` and the other deps are updated as well

**Comment by pesterhazy** [comment]
glad to hear that! Did you need the `:disable-hud` flag?

**Comment by vikeri** [comment]
Nope, just had some tasks running that should not be running
