### ISSUE TITLE
Update boot-react-native master

### ISSUE THREAD

**Issue by pesterhazy** [mjmeintjes/boot-react-native#59]
Current master has been broken for a while. It'd be great to get master back to a working version again.

In my view, master should:

- work with curren React Native versions
- have SimpleExampleApp start out of the box (after `npm install`)
- reloading works
- work out of the box with iOS and android

My proposal would be to replace master with my branch, https://github.com/pesterhazy/boot-react-native/tree/develop. The branch is based on an earlier point in the repo history, before https://github.com/mjmeintjes/boot-react-native/pull/46 was merged.

I've started creating issues so we can track the remaining problems with the develop branch, but I think it's progress in the right direction.

@mjmeintjes, what do you think? I'd love to see progress on this soon, as there's quite a bit of interest in BRN nowadays. I'd like to squash the commits in my branch and polish things a bit, but otherwise I think it's good to go (though would love to see more testing of course).

**Comment by pesterhazy** [comment]
develop fixes at least https://github.com/mjmeintjes/boot-react-native/issues/56, https://github.com/mjmeintjes/boot-react-native/issues/54, https://github.com/mjmeintjes/boot-react-native/issues/52 and https://github.com/mjmeintjes/boot-react-native/issues/49.

**Comment by mjmeintjes** [comment]
@pesterhazy I agree with you, and fully support replacing master with your branch.

I'm currently not able to spend a lot of time on this, due to other commitments. Would you be interested in commit rights on this repository, as you've been doing most of the recent work anyway?

**Comment by pesterhazy** [comment]
@mjmeintjes, that'd be great, yes!

**Comment by pesterhazy** [comment]
Todo to get this merged:

- [ ] squash commits
- [ ] get rid of silly test files (hello.js)
- [ ] test on android

**Comment by pesterhazy** [comment]
Getting closer. Reloading works now for both android and ios. Major outstanding issue is https://github.com/mjmeintjes/boot-react-native/issues/57

**Comment by pesterhazy** [comment]
slow reloading is fixed now

**Comment by pesterhazy** [comment]
@mjmeintjes, https://github.com/pesterhazy/boot-react-native/tree/develop is now ready to replace `master`. I added some update notes here: https://github.com/pesterhazy/boot-react-native/blob/develop/changelog.md

More documentation (getting started etc.) should be added soon, but I'd rather not delay getting the code into master so people can play with it

**Comment by pesterhazy** [comment]
Done; `master` now points at the 0.3 branch. The old `master` is still available as `old/master`.

I've added release notes with notes on how to upgrade (there's a manual step involved). I've also added a link to a Getting Started guide (http://presumably.de/boot-react-native.html), and hope to continue with that series.
