### ISSUE TITLE
RN 0.31.0 breaks boot-reload and cljs-repl

### ISSUE THREAD

**Issue by vikeri** [mjmeintjes/boot-react-native#70]
After upgrading to RN 0.31.0 boot-reload and cljs-repl no longer work.

**Comment by pesterhazy** [comment]
That's only on Android, correct?

I don't see anything in the Release Notes related to websockets. Any idea what change broke boot-reload's websocket connections?

**Comment by vikeri** [comment]
Correct, only on Android. Might be the same as this: https://github.com/facebook/react-native/issues/9523

**Comment by vikeri** [comment]
Fixed in RN 0.32.0
