### ISSUE TITLE
boot dev error: java.lang.IllegalArgumentException: Cannot open <nil> as a Reader

### ISSUE THREAD

**Issue by tiensonqin** [mjmeintjes/boot-react-native#83]
`boot dev` shows: 
Starting reload server on ws://localhost:8079
Writing adzerk/boot_reload/init2372.cljs to connect to ws://localhost:8079...
Writing boot_cljs_repl.cljs...
             clojure.lang.ExceptionInfo: java.lang.IllegalArgumentException: Cannot open <nil> as a Reader.
    data: {:file "/tmp/boot.user8910946252566361795.clj", :line 19}
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot open <nil> as a Reader.
     java.lang.IllegalArgumentException: Cannot open <nil> as a Reader.
                              clojure.java.io/fn/invokeStatic                 io.clj:  288
                                           clojure.java.io/fn                 io.clj:  288
                                         clojure.java.io/fn/G                 io.clj:   69
                          clojure.java.io/reader/invokeStatic                 io.clj:  102
                                       clojure.java.io/reader                 io.clj:   86
                                                          ...                             
                              clojure.core/apply/invokeStatic               core.clj:  648
                              clojure.core/slurp/invokeStatic               core.clj: 6657
                                           clojure.core/slurp               core.clj: 6657
                                                          ...                             
        mattsum.impl.boot-helpers/read-resource-/invokeStatic       boot_helpers.clj:   15
                     mattsum.impl.boot-helpers/read-resource-       boot_helpers.clj:   13
                                                          ...                             
                              clojure.core/apply/invokeStatic               core.clj:  646
                                      clojure.core/memoize/fn               core.clj: 6107
                                                          ...                             
mattsum.impl.boot-helpers/write-resource-to-path/invokeStatic       boot_helpers.clj:   88
             mattsum.impl.boot-helpers/write-resource-to-path       boot_helpers.clj:   83
                  mattsum.boot-react-native/eval2233/fn/fn/fn  boot_react_native.clj:  304
                                          boot.core/run-tasks               core.clj:  794
                                            boot.core/boot/fn               core.clj:  804
                          clojure.core/binding-conveyor-fn/fn               core.clj: 1938

**Comment by tiensonqin** [comment]
After copy resources to example/resources, it works.
New to boot, I thought local installed jar should include the resources.

Anyway, great work!
I'll close this one.

**Comment by vikeri** [comment]
Also ran into this now when updating, didn't have that issue before. Pretty sure the jar should include the sources...

**Comment by vikeri** [comment]
Confirmed that it was a regression error, submitted a PR
