### ISSUE TITLE
Remove boot-react-native

### ISSUE THREAD

**Issue by mfikes** [mjmeintjes/boot-react-native#88]
From @vikeri : remove boot-react-native since it hasn't been maintained in a long time now (
https://twitter.com/cviktore/status/1096301630914523136)

**Comment by pesterhazy** [comment]
Thanks for the note!. Yes, please remove boot-react-native from cljsrn.org - it's unmaintained (by me). It would require significant effort to make it work with current versions of react-native; and re-natal's design is fundamentally better anyway.

**Comment by mjmeintjes** [comment]
Hi. Just noticed this. Would you be ok if I archived this repository?

**Comment by pesterhazy** [comment]
@mjmeintjes I think that's an excellent idea
